  CREATE TABLE "COMM" 
   (	"COMM_NUM" NUMBER, 
	"COMM_NAME" VARCHAR2(30 BYTE), 
	"COMM_PASS" VARCHAR2(30 BYTE), 
	"COMM_CONTENT" VARCHAR2(200 BYTE), 
	"COMM_BOARD_NUM" NUMBER, 
	"COMM_RE_REF" NUMBER, 
	"COMM_RE_LEV" NUMBER(1,0), 
	"COMM_RE_SEQ" NUMBER, 
	"COMM_REG_DATE" DATE DEFAULT SYSDATE   --댓글 작성일
    
   );


  CREATE UNIQUE INDEX "SYS_C007155" ON "COMM" ("COMM_NUM");


  ALTER TABLE "COMM" ADD PRIMARY KEY ("COMM_NUM") ENABLE;
  ALTER TABLE "COMM" ADD CHECK (COMM_RE_LEV IN (0,1,2)) ENABLE;
  ALTER TABLE "COMM" MODIFY ("COMM_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "COMM" MODIFY ("COMM_PASS" NOT NULL ENABLE);


  ALTER TABLE "COMM" ADD FOREIGN KEY ("COMM_BOARD_NUM")
	  REFERENCES "FREE" ("FREE_NUM") ON DELETE CASCADE ENABLE;