CREATE TABLE "COMPANY_INFO" 
   (	"COMPANY_NAME" VARCHAR2(50 BYTE), 
	"COMPANY_URL" VARCHAR2(100 BYTE), 
	"COMPANY_LOGO" VARCHAR2(100 BYTE), 
	"COMPANY_CSV_FORM" VARCHAR2(100 BYTE), 
	"USER_ID" VARCHAR2(30 BYTE)
   );
   
   Insert into COMPANY_INFO (COMPANY_NAME,COMPANY_URL,COMPANY_LOGO,COMPANY_CSV_FORM,USER_ID) values ('CO-WORK','WWW.COWORK.RUN','Brick_300x1002.jpg',null,'HTA1');
   
   CREATE UNIQUE INDEX "COMPANY_INFO_PK" ON "COMPANY_INFO" ("COMPANY_NAME");
   
   ALTER TABLE "COMPANY_INFO" ADD CONSTRAINT "COMPANY_INFO_PK" PRIMARY KEY ("COMPANY_NAME") ENABLE;
  ALTER TABLE "COMPANY_INFO" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);

  ALTER TABLE "COMPANY_INFO" ADD CONSTRAINT "COMPANY_INFO_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "USER_INFO" ("USER_ID") ENABLE;