CREATE TABLE "COMPANY_DEPT" 
   (	"DEPT_NAME" VARCHAR2(50 BYTE), 
	"COMPANY_NAME" VARCHAR2(50 BYTE)
   );
   
   Insert into COMPANY_DEPT (DEPT_NAME,COMPANY_NAME) values ('인사','CO-WORK');
Insert into COMPANY_DEPT (DEPT_NAME,COMPANY_NAME) values ('총무','CO-WORK');
Insert into COMPANY_DEPT (DEPT_NAME,COMPANY_NAME) values ('개발1팀','CO-WORK');
Insert into COMPANY_DEPT (DEPT_NAME,COMPANY_NAME) values ('생산','CO-WORK');
Insert into COMPANY_DEPT (DEPT_NAME,COMPANY_NAME) values (null,'CO-WORK');

ALTER TABLE "COMPANY_DEPT" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);

ALTER TABLE "COMPANY_DEPT" ADD CONSTRAINT "COMPANY_DEPT_FK1" FOREIGN KEY ("COMPANY_NAME")
	  REFERENCES "COMPANY_INFO" ("COMPANY_NAME") ENABLE;