  CREATE TABLE "NOTICE" 
   (	"NOTICE_NUM" NUMBER, 
	"USER_ID" VARCHAR2(30 BYTE), 
	"NOTICE_SUBJECT" VARCHAR2(300 BYTE), 
	"NOTICE_CONTENT" VARCHAR2(4000 BYTE), 
	"NOTICE_FILE" VARCHAR2(50 BYTE), 
	"NOTICE_RE_REF" NUMBER, 
	"NOTICE_RE_LEV" NUMBER, 
	"NOTICE_RE_SEQ" NUMBER, 
	"NOTICE_READCOUNT" NUMBER, 
	"NOTICE_REG_DATE" DATE DEFAULT SYSDATE
   );
   
  Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (1,'HTA1','공지사항1','공지사항1내용입니다.',null,1,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (2,'HTA1','공지사항2','공지사항2내용입니다.',null,2,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (3,'HTA1','공지사항3','공지사항3내용입니다.',null,3,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (4,'HTA1','공지사항4','공지사항4내용입니다.',null,4,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (5,'HTA1','공지사항5','공지사항5내용입니다.',null,5,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (6,'HTA1','공지사항6','공지사항6내용입니다.',null,6,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (7,'HTA1','공지사항7','공지사항7내용입니다.',null,7,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (8,'HTA1','공지사항8','공지사항8내용입니다.',null,8,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (9,'HTA1','공지사항9','공지사항9내용입니다.',null,9,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (10,'HTA1','공지사항10','공지사항10내용입니다.',null,10,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (11,'HTA1','공지사항11','공지사항11내용입니다.',null,11,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (12,'HTA1','공지사항12','공지사항12내용입니다.',null,12,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (13,'HTA1','공지사항13','공지사항13내용입니다.',null,13,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (14,'HTA1','공지사항14','공지사항14내용입니다.',null,14,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (15,'HTA1','공지사항15','공지사항15내용입니다.',null,15,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (16,'HTA1','공지사항16','공지사항16내용입니다.',null,16,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (17,'HTA1','공지사항17','공지사항17내용입니다.',null,17,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (18,'HTA1','공지사항18','공지사항18내용입니다.',null,18,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (19,'HTA1','공지사항19','공지사항19내용입니다.',null,19,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (20,'HTA1','공지사항20','공지사항20내용입니다.',null,20,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (21,'HTA1','공지사항21','공지사항21내용입니다.',null,21,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (22,'HTA1','공지사항22','공지사항22내용입니다.',null,22,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (23,'HTA1','공지사항23','공지사항23내용입니다.',null,23,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (24,'HTA1','공지사항24','공지사항24내용입니다.',null,24,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (25,'HTA1','공지사항25','공지사항25내용입니다.',null,25,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (26,'HTA1','공지사항26','공지사항26내용입니다.',null,26,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (27,'HTA1','공지사항27','공지사항27내용입니다.',null,27,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (28,'HTA1','공지사항28','공지사항28내용입니다.',null,28,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (29,'HTA1','공지사항29','공지사항29내용입니다.',null,29,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (30,'HTA1','공지사항30','공지사항30내용입니다.',null,30,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (31,'HTA1','공지사항31','공지사항31내용입니다.',null,31,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (32,'HTA1','공지사항32','공지사항32내용입니다.',null,32,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (33,'HTA1','공지사항33','공지사항33내용입니다.',null,33,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (34,'HTA1','공지사항34','공지사항34내용입니다.',null,34,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (35,'HTA1','공지사항35','공지사항35내용입니다.',null,35,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (36,'HTA1','공지사항36','공지사항36내용입니다.',null,36,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (37,'HTA1','공지사항37','공지사항37내용입니다.',null,37,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (38,'HTA1','공지사항38','공지사항38내용입니다.',null,38,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (39,'HTA1','공지사항39','공지사항39내용입니다.',null,39,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (40,'HTA1','공지사항40','공지사항40내용입니다.',null,40,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (41,'HTA1','공지사항41','공지사항41내용입니다.',null,41,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (42,'HTA1','공지사항42','공지사항42내용입니다.',null,42,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (43,'HTA1','공지사항43','공지사항43내용입니다.',null,43,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (44,'HTA1','공지사항44','공지사항44내용입니다.',null,44,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (45,'HTA1','공지사항45','공지사항45내용입니다.',null,45,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (46,'HTA1','공지사항46','공지사항46내용입니다.',null,46,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (47,'HTA1','공지사항47','공지사항47내용입니다.',null,47,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (48,'HTA1','공지사항48','공지사항48내용입니다.',null,48,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (49,'HTA1','공지사항49','공지사항49내용입니다.',null,49,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (50,'HTA1','공지사항50','공지사항50내용입니다.',null,50,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (51,'HTA1','공지사항51','공지사항51내용입니다.',null,51,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (52,'HTA1','공지사항52','공지사항52내용입니다.',null,52,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (53,'HTA1','공지사항53','공지사항53내용입니다.',null,53,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (54,'HTA1','공지사항54','공지사항54내용입니다.',null,54,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (55,'HTA1','공지사항55','공지사항55내용입니다.',null,55,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (56,'HTA1','공지사항56','공지사항56내용입니다.',null,56,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (57,'HTA1','공지사항57','공지사항57내용입니다.',null,57,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (58,'HTA1','공지사항58','공지사항58내용입니다.',null,58,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (59,'HTA1','공지사항59','공지사항59내용입니다.',null,59,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (60,'HTA1','공지사항60','공지사항60내용입니다.',null,60,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (61,'HTA1','공지사항61','공지사항61내용입니다.',null,61,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (62,'HTA1','공지사항62','공지사항62내용입니다.',null,62,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (63,'HTA1','공지사항63','공지사항63내용입니다.',null,63,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (64,'HTA1','공지사항64','공지사항64내용입니다.',null,64,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (65,'HTA1','공지사항65','공지사항65내용입니다.',null,65,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (66,'HTA1','공지사항66','공지사항66내용입니다.',null,66,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (67,'HTA1','공지사항67','공지사항67내용입니다.',null,67,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (68,'HTA1','공지사항68','공지사항68내용입니다.',null,68,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (69,'HTA1','공지사항69','공지사항69내용입니다.',null,69,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (70,'HTA1','공지사항70','공지사항70내용입니다.',null,70,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (71,'HTA1','공지사항71','공지사항71내용입니다.',null,71,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (72,'HTA1','공지사항72','공지사항72내용입니다.',null,72,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (73,'HTA1','공지사항73','공지사항73내용입니다.',null,73,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (74,'HTA1','공지사항74','공지사항74내용입니다.',null,74,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (75,'HTA1','공지사항75','공지사항75내용입니다.',null,75,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (76,'HTA1','공지사항76','공지사항76내용입니다.',null,76,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (77,'HTA1','공지사항77','공지사항77내용입니다.',null,77,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (78,'HTA1','공지사항78','공지사항78내용입니다.',null,78,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (79,'HTA1','공지사항79','공지사항79내용입니다.',null,79,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (80,'HTA1','공지사항80','공지사항80내용입니다.',null,80,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (81,'HTA1','공지사항81','공지사항81내용입니다.',null,81,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (82,'HTA1','공지사항82','공지사항82내용입니다.',null,82,0,0,0,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (83,'HTA1','공지사항83','공지사항83내용입니다.',null,83,0,0,1,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (84,'HTA1','공지사항84','공지사항84내용입니다.',null,84,0,0,1,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (85,'HTA1','asd','asdasd',null,85,0,0,2,to_date('23/02/14','RR/MM/DD'));
Insert into NOTICE (NOTICE_NUM,USER_ID,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_FILE,NOTICE_RE_REF,NOTICE_RE_LEV,NOTICE_RE_SEQ,NOTICE_READCOUNT,NOTICE_REG_DATE) values (86,'HTA1','asd','asdasdsadasd','2392A3~1.JFI',86,0,0,5,to_date('23/02/14','RR/MM/DD')); 
   

CREATE UNIQUE INDEX "SYS_C007145" ON "NOTICE" ("NOTICE_NUM");


  ALTER TABLE "NOTICE" ADD PRIMARY KEY ("NOTICE_NUM") ENABLE;
  ALTER TABLE "NOTICE" MODIFY ("NOTICE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "NOTICE" MODIFY ("NOTICE_SUBJECT" NOT NULL ENABLE);
  
  ALTER TABLE "NOTICE" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "USER_INFO" ("USER_ID") ENABLE;
	  
