DROP TABLE PROJECT_BOARD_COMMENT;

select * from PROJECT_BOARD_COMMENT;

--PROJECT_NUM 시퀀스 생성
CREATE SEQUENCE PROJECT_BOARD_COMMENT_SEQ
INCREMENT BY 1
START WITH 1;

--데이터 삭제 시 시퀀스 -1
ALTER SEQUENCE PROJECT_BOARD_COMMENT
INCREMENT BY -1;

SELECT PROJECT_BOARD_COMMENT.NEXTVAL
FROM dual;
 
ALTER SEQUENCE PROJECT_BOARD_COMMENT_SEQ
INCREMENT BY 1;

--시퀀스 삭제
DROP SEQUENCE PROJECT_BOARD_SEQ

CREATE TABLE PROJECT_BOARD_COMMENT(
PRO_BO_COMMENT_NUM 			NUMBER PRIMARY KEY NOT NULL, 
PRO_BO_COMMENT_ID			VARCHAR2(30) NOT NULL, 
PRO_BO_COMMENT_NAME			VARCHAR2(30) NOT NULL, 
PRO_BO_COMMENT_SUBJECT		VARCHAR2(500), 
PRO_BO_COMMENT_CONTENT		VARCHAR2(1000), 
PRO_BO_COMMENT_FILE			VARCHAR2(50) NOT NULL,
PRO_BO_COMMENT_RE_REF		NUMBER NOT NULL, 
PRO_BO_COMMENT_RE_LEV		NUMBER, 
PRO_BO_COMMENT_RE_SEQ		NUMBER, 
PRO_BO_COMMENT_DATE			DATE, 
PRO_BOARD_NUM				NUMBER NOT NULL,
FOREIGN KEY(PRO_BO_COMMENT_ID) REFERENCES USER_INFO(USER_ID) ON DELETE CASCADE,
FOREIGN KEY(PRO_BOARD_NUM) REFERENCES PROJECT_BOARD(PRO_BOARD_NUM) ON DELETE CASCADE
);

INSERT INTO PROJECT_BOARD_COMMENT(
PRO_BO_COMMENT_NUM, PRO_BO_COMMENT_ID, PRO_BO_COMMENT_NAME,
PRO_BO_COMMENT_FILE, PRO_BO_COMMENT_RE_REF, PRO_BOARD_NUM)
VALUES('1', 'HTA1', '홍길동', 
'파일', '1', 1);

INSERT INTO PROJECT_BOARD_COMMENT(
PRO_BO_COMMENT_NUM, PRO_BO_COMMENT_ID, PRO_BO_COMMENT_NAME,
PRO_BO_COMMENT_FILE, PRO_BO_COMMENT_RE_REF, PRO_BOARD_NUM)
VALUES('2', 'HTA2', '멤버1', 
'파일', '1', 2);

INSERT INTO PROJECT_BOARD_COMMENT(
PRO_BO_COMMENT_NUM, PRO_BO_COMMENT_ID, PRO_BO_COMMENT_NAME,
PRO_BO_COMMENT_FILE, PRO_BO_COMMENT_RE_REF, PRO_BOARD_NUM)
VALUES('3', 'HTA3', '멤버2', 
'파일', '1', 3);