CREATE TABLE "PROJECT_USER" 
   (	"PROJECT_NUM" NUMBER(10,0), 
	"USER_ID" VARCHAR2(30 BYTE), 
	"PROJECT_USER_NO" VARCHAR2(20 BYTE) DEFAULT 0
   );
   
   Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (9,'HTA1','4');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (10,'HTA3','15');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (7,'HTA3','14');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (8,'HTA2','11');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (1,'HTA1','1');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (2,'HTA2','12');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (2,'HTA4','18');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (2,'HTA6','22');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (2,'HTA1','3');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (3,'HTA3','13');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (3,'HTA2','7');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (3,'HTA1','6');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (4,'HTA8','27');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (4,'HTA7','24');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (2,'HTA7','23');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (3,'HTA4','19');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (2,'HTA3','17');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (5,'HTA1','2');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (6,'HTA1','5');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (4,'HTA2','9');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (5,'HTA4','20');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (5,'HTA5','21');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (4,'HTA3','16');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (6,'HTA2','10');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (7,'HTA9','28');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (8,'HTA7','26');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (10,'HTA2','8');
Insert into PROJECT_USER (PROJECT_NUM,USER_ID,PROJECT_USER_NO) values (9,'HTA7','25');

CREATE UNIQUE INDEX "PROJECT_USER_PK" ON "PROJECT_USER" ("PROJECT_USER_NO");

 ALTER TABLE "PROJECT_USER" ADD CONSTRAINT "PROJECT_USER_PK" PRIMARY KEY ("PROJECT_USER_NO") ENABLE;
  ALTER TABLE "PROJECT_USER" MODIFY ("PROJECT_NUM" NOT NULL ENABLE);
  ALTER TABLE "PROJECT_USER" MODIFY ("PROJECT_USER_NO" NOT NULL ENABLE);
  
    ALTER TABLE "PROJECT_USER" ADD FOREIGN KEY ("PROJECT_NUM")
	  REFERENCES "PROJECT" ("PROJECT_NUM") ON DELETE CASCADE ENABLE;
  ALTER TABLE "PROJECT_USER" ADD FOREIGN KEY ("USER_ID")
	  REFERENCES "USER_INFO" ("USER_ID") ON DELETE CASCADE ENABLE;
	  
